### ISSUE TITLE
Looks like this plugin is broken with nativescript 4

### ISSUE THREAD

**Issue by yalva** [bthurlow/nativescript-maskedinput#19]
System.err: TypeError: Cannot read property 'addTextChangedListener' of undefined
System.err: File: "file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/nativescript-maskedinput/maskedinput.js, line: 50, column: 21
System.err: StackTrace:
System.err: 	Frame: function:'MaskedInput._configureEditText', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/nativescript-maskedinput/maskedinput.js', line: 50, column: 22
System.err: 	Frame: function:'EditableTextBase.createNativeView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/editable-text-base/editable-text-base.js', line: 117, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 492, column: 35
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err: 	Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err: 	Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err: 	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 588, column: 24
System.err: 	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.testmaskedinput/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err: 	at android.app.Fragment.performCreateView(Fragment.java:2220)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
System.err: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
System.err: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process org.nativescript.testmaskedinput (pid 14013) has died

**Comment by shiv19** [comment]
Please use this plugin instead
https://github.com/PeterStaev/nativescript-masked-text-field
